export const Messages = {
  USER_CREATED: 'User created. Please verify your email by entering the OTP sent to your email.',
  USER_EXISTS: 'User with this email already exists.',
  OTP_INVALID: 'Invalid OTP or OTP has expired.',
  USER_NOT_FOUND: 'User not found.',
  EMAIL_VERIFIED: 'Email verified successfully!',
  INVALID_PASSWORD: 'Invalid password.',
  VERIFY_EMAIL: 'Please verify your email before logging in.',
  UNKNOWN_ERROR: 'An unknown error occurred.',
  USER_UPDATED: 'User updated successfully.',
  RECRUITER_CREATED: 'Recruiter created. Please verify your email by entering the OTP sent to your email.',
  RECRUITER_EXISTS: 'Recruiter with this email already exists.',
  LOGIN_SUCCESS: 'Login successful',
  JOB_CATEGORY_CREATED: 'Job Category created successfully.',
  JOB_CATEGORY_UPDATED: 'Job Category updated successfully.',
  JOB_CATEGORY_DELETED: 'Job Category deleted successfully.',
  JOB_CATEGORY_NOT_FOUND: 'Job Category not found.',
  JOB_CATEGORY_EXISTS: 'Job Category with this name already exists.',
  INVALID_DATA_PROVIDED: 'Invalid data provided.',
  COMPANY_NOT_FOUND: 'Company not found.',
  RECRUITER_ID_REQUIRED: 'Recruiter ID is required.',
  USER_ID_REQUIRED: 'User ID is required.',
  COMPANY_NOT_FOUND_FOR_RECRUITER: 'Company not found for this recruiter.',
  JOB_NOT_FOUND: 'Job not found.',
  APPLICATION_SUCCESSFUL: 'Application successful.',
  NO_APPLIED_JOBS_FOUND: 'No applied jobs found.',
  NO_JOBS_FOUND_FOR_RECRUITER: 'No jobs found for this recruiter.',
  REFRESH_TOKEN_MISSING: 'Refresh token missing',
  INVALID_OR_EXPIRED_REFRESH_TOKEN: 'Invalid or expired refresh token',
  RECRUITER_NOT_FOUND: 'Recruiter not found.', 
  RECRUITER_BLOCKED_OR_UNBLOCKED: 'Recruiter blocked or unblocked successfully.', 
  USER_BLOCKED_OR_UNBLOCKED: 'User blocked or unblocked successfully.', 
  COMPANY_NOT_FOUND_HR_ID: 'Company not found for the provided HR ID.',
  COMPANY_CREATED: 'Company created successfully.',
  COMPANY_UPDATED: 'Company updated successfully.',
  JOB_CREATED: 'Job created successfully.',
  JOB_UPDATED: 'Job updated successfully.',
  JOB_DELETED: 'Job deleted successfully.',
  INVALID_USER_ID: 'Invalid user ID provided.',
};
