name: CI/CD Pull Latest Code and Deploy to AWS EC2

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Debug SSH Key (optional)
      - name: Debug SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY}}" > debug_key.pem
          chmod 600 debug_key.pem
          ssh-keygen -lf debug_key.pem || echo "Invalid key format"

      # Step 3: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 4: Deploy to EC2
      - name: Deploy to EC2 instance
        run: |
          ssh -T -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd FINDY  # Replace with your actual path
            git pull origin main
            cd back-end
            if [[ ! -d "node_modules" || $(git diff --name-only origin/main | grep package.json) ]]; then
              npm install
            fi
            if [[ $(git diff --name-only origin/main | grep -E '\.(js|ts|jsx|tsx)$') ]]; then
              npm run build
            fi
            pm2 restart all
            pm2 status
          EOF
