name: CI/CD Pull Latest Code and Deploy to AWS EC2

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Debug the SSH Key
      - name: Debug SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
          ssh-keygen -lf key.pem

      # Step 4: Deploy to EC2 instance
      - name: Deploy to EC2 instance
        run: |
          ssh -T -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Navigate to the correct directory on the EC2 instance (adjust if needed)
            cd FINDY  # VERY IMPORTANT: Replace with your actual path!

            # Pull the latest code for the entire repository
            git pull origin main

            # Navigate to the backend directory
            cd back-end

            # Install dependencies (only if package.json has changed)
            if [[ ! -d "node_modules" || $(git diff --name-only origin/main | grep package.json) ]]; then
              echo "package.json changed or node_modules missing, installing dependencies"
              npm install
            fi

            # Build the backend (only if source code has changed)
            if [[ $(git diff --name-only origin/main | grep -E '\.(js|ts|jsx|tsx)$') ]]; then
              echo "Source code changed, building the backend"
              npm run build # Or your build command (e.g., tsc)
            fi

            # Restart the backend application using pm2
            pm2 restart all

            # Optional: Display pm2 status for debugging
            pm2 status
          EOF
